---

- name: Install deps
  yum:
    pkg: [
      "adduser",
      "libfontconfig1",
      "apt-transport-https"
    ]
    state: present

- name: Download deb file
  get_url:
    url: "https://mirrors.tuna.tsinghua.edu.cn/grafana/yum/rpm/grafana-{{ version }}-1.x86_64.rpm"
    dest: "/tmp/grafana.deb"
    mode: "0755"
    checksum: "sha256:{{ sha256sum }}"

- name: Install grafana
  apt:
    deb: "/tmp/grafana.deb"
    state: present
  notify: start grafana

- name: Cleanup grafana deb file
  file:
    path: "/tmp/grafana.deb"
    state: absent
