---

prometheus_version: "2.22.1"
prometheus_sha256sum: "9001a9cb939e0a6d9f2b67d22506c620bc9457777272fced43274b032ba35f44"
prometheus_tar_url: "https://mirrors.tuna.tsinghua.edu.cn/github-release/prometheus/prometheus/LatestRelease/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"