---

prometheus_version: "2.30.0"
prometheus_sha256sum: "49c0809d4983f91c9afb8d260b36b821e90a6dcb82d0bad605ff9a3102a9e6d8"
prometheus_tar_url: "https://mirrors.tuna.tsinghua.edu.cn/github-release/prometheus/prometheus/LatestRelease/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
